/**
 * @ngdoc property
 * @name vbet5.constant:LanguageSwitchConfig
 * @description Language Switch based on the country code
 */
angular.module('vbet5').constant('GeoIPLangSwitch', {

    'default': 'rus',
    'bangladesh': 'eng',
    'brunei': 'eng',
    'equatorial guinea': 'eng',
    'ethiopia': 'eng',
    'laos': 'eng',
    'pakistan': 'eng',
    'qatar': 'eng',
    'moldova': 'rus',
    'cyprus': 'tur',
    'armenia': 'arm',
    'myanmar': 'eng',
    'belgium': 'eng',
    'saudi arabia': 'eng',
    'yemen': 'eng',
    'antigua and barbuda': 'eng',
    'barbados': 'eng',
    'belize': 'eng',
    'botswana': 'eng',
    'cambodia': 'eng',
    'cameroon': 'eng',
    'denmark': 'eng',
    'east timor': 'eng',
    'fiji': 'eng',
    'greece': 'gre',
    'grenada': 'eng',
    'guyana': 'eng',
    'iceland': 'eng',
    'india': 'eng',
    'indonesia': 'eng',
    'iran': 'eng',
    'iraq': 'eng',
    'ireland': 'eng',
    'israel': 'eng',
    'jamaica': 'eng',
    'japan': 'eng',
    'jordan': 'eng',
    'kiribati': 'eng',
    'korea, north': 'eng',
    'korea, south': 'eng',
    'korea': 'eng',
    'kosovo': 'eng',
    'kuwait': 'eng',
    'lebanon': 'eng',
    'liechtenstein': 'eng',
    'luxembourg': 'eng',
    'macedonia': 'eng',
    'madagascar': 'eng',
    'malawi': 'eng',
    'malaysia': 'eng',
    'maldives': 'eng',
    'mali': 'eng',
    'malta': 'eng',
    'marshall islands': 'eng',
    'mauritania': 'eng',
    'mauritius': 'eng',
    'monaco': 'eng',
    'montenegro': 'eng',
    'morocco': 'eng',
    'mozambique': 'eng',
    'nauru': 'eng',
    'nepal': 'eng',
    'netherlands': 'eng',
    'new zealand': 'eng',
    'niger': 'eng',
    'nigeria': 'eng',
    'norway': 'eng',
    'oman': 'eng',
    'palau': 'eng',
    'palestinian state': 'eng',
    'papua new guinea': 'eng',
    'philippines': 'eng',
    'poland': 'eng',
    'romania': 'eng',
    'st. kitts and nevis': 'eng',
    'st. lucia': 'eng',
    'samoa': 'eng',
    'senegal': 'eng',
    'serbia': 'eng',
    'seychelles': 'eng',
    'sierra leone': 'eng',
    'singapore': 'eng',
    'slovakia': 'eng',
    'slovenia': 'eng',
    'solomon islands': 'eng',
    'somalia': 'eng',
    'south africa': 'eng',
    'south sudan': 'eng',
    'sri lanka': 'eng',
    'sudan': 'eng',
    'suriname': 'eng',
    'swaziland': 'eng',
    'sweden': 'eng',
    'switzerland': 'eng',
    'syria': 'eng',
    'taiwan': 'eng',
    'tanzania': 'eng',
    'thailand': 'eng',
    'togo': 'eng',
    'tonga': 'eng',
    'trinidad and tobago': 'eng',
    'tunisia': 'eng',
    'tuvalu': 'eng',
    'uganda': 'eng',
    'united arab emirates': 'eng',
    'united kingdom': 'eng',
    'united states': 'eng',
    'vanuatu': 'eng',
    'vietnam': 'eng',
    'western sahara': 'eng',
    'bulgaria': 'eng',
    'australia': 'eng',
    'bahamas': 'eng',
    'canada': 'eng',
    'dominica': 'eng',
    'egypt': 'eng',
    'gambia': 'eng',
    'ghana': 'eng',
    'kenya': 'eng',
    'liberia': 'eng',
    'micronesia': 'eng',
    'namibia': 'eng',
    'rwanda': 'eng',
    'zambia': 'eng',
    'zimbabwe': 'eng',
    'albania': 'eng',
    'bhutan': 'eng',
    'bosnia and herzegovina': 'eng',
    'central african republic': 'eng',
    'chad': 'eng',
    'china': 'eng',
    'comoros': 'eng',
    'congo, democratic republic of the': 'eng',
    'congo, republic of': 'eng',
    'croatia': 'eng',
    'czech republic': 'eng',
    'djibouti': 'eng',
    'eritrea': 'eng',
    'finland': 'eng',
    'france': 'eng',
    'gabon': 'eng',
    'germany': 'ger',
    'guinea': 'eng',
    'guinea-bissau': 'eng',
    'haiti': 'eng',
    'hungary': 'eng',
    'bahrain': 'eng',
    'lesotho': 'eng',
    'algeria': 'fra',
    'andorra': 'fra',
    'benin': 'fra',
    'burkina faso': 'fra',
    'burundi': 'fra',
    'austria': 'de',
    'libya': 'ita',
    'san marino': 'ita',
    'vatican city': 'ita',
    'italy': 'ita',
    'angola': 'por',
    'brazil': 'por',
    'cape verde': 'por',
    'portugal': 'por',
    'belarus': 'rus',
    'estonia': 'rus',
    'georgia': 'rus',
    'kyrgyzstan': 'rus',
    'latvia': 'rus',
    'lithuania': 'rus',
    'mongolia': 'rus',
    'russia': 'rus',
    'tajikistan': 'rus',
    'turkmenistan': 'rus',
    'ukraine': 'rus',
    'uzbekistan': 'rus',
    'kazakhstan': 'rus',
    'chile': 'spa',
    'colombia': 'spa',
    'cuba': 'spa',
    'dominican republic': 'spa',
    'ecuador': 'spa',
    'el salvador': 'spa',
    'honduras': 'spa',
    'panama': 'spa',
    'paraguay': 'spa',
    'peru': 'spa',
    'uruguay': 'spa',
    'venezuela': 'spa',
    'argentina': 'spa',
    'guatemala': 'spa',
    'nicaragua': 'spa',
    'spain': 'spa',
    'costa rica': 'spa',
    'bolivia': 'spa',
    'mexico': 'spa',
    'afghanistan': 'tur',
    'azerbaijan': 'tur',
    'turkey': 'tur'
});


